-- 'Список выполненных работ, фиксирующих дату оплаты заявки, заказчиков, код услуги, фамилию исполнителя’
select luch_schema.order.date_payment, client.full_name, content_order.service_id, worker.full_name from luch_schema.order join luch_schema.client on luch_schema.order.client_id = client.id join luch_schema.content_order on luch_schema.order.id = content_order.order_id join luch_schema.worker on worker.id = content_order.worker_id join luch_schema.price_list on content_order.service_id = price_list.id where luch_schema.order.status = 'paid';
-- 'Список платежных поручений, выставленных рекламодателям за любой промежуток времени, фиксирующий заказчика, услугу, состояние заявки (оплачено или нет)
select client.full_name, price_list.service, luch_schema.order.status from luch_schema.order join luch_schema.client on luch_schema.order.client_id = client.id join luch_schema.content_order on luch_schema.order.id = content_order.order_id join luch_schema.worker on worker.id = content_order.worker_id join luch_schema.price_list on content_order.service_id = price_list.id where content_order.date_forming between '2018-01-19' and '2018-01-25'; 
-- 'Просмотр номенклатуры рекламных услуг, предлагаемых агентством по видам услуг’
select service, price from luch_schema.price_list order by service;
-- 'Список заявок, заключенных каждым отдельным заказчиком за любой промежуток времени’
select client.full_name, luch_schema.order.id from luch_schema.order join luch_schema.client on client.id = luch_schema.order.client_id join luch_schema.content_order on content_order.order_id = luch_schema.order.id where content_order.date_forming between '2018-01-19' and '2018-01-25'; 
-- 'Список сотрудников с указанием количества заявок, которые выполнял каждый сотрудник в заданный период’
select worker.full_name, count(content_order.order_id) from luch_schema.worker join luch_schema.content_order on worker.id = luch_schema.content_order.worker_id where content_order.date_forming between '2018-01-19' and '2018-01-25' group by worker.id; 
 -- 'Список сотрудников с указанием общей стоимости выполненных ими заказов’
select worker.full_name, sum(content_order.final_price) from luch_schema.worker join luch_schema.content_order on worker.id = luch_schema.content_order.worker_id where content_order.date_forming between '2018-01-03' and '2018-01-19' group by worker.id; 
-- 'Список услуг и значение 'Category', которое будет отображать стоимость услуги: 'Premium', если стоимость больше 90, и 'Basic' в остальных случаях’
 select service, case when price_list.price > 90 then 'Premium' else 'Basic' end as Category from luch_schema.price_list;
-- 'Вывести пары сотрудник-клиент и стоимость выполненного заказа. Для невыполненных заказов в стоимости указать 0, для сотрудников, не работающих над заказами, вывести прочерк в графе клиент и 0 в графе стоимость. '
-- 'Сотрудники могут работать над несколькими заказами’
select distinct worker.full_name as worker, client.full_name as client, content_order.final_price as price from luch_schema.worker left join luch_schema.content_order on worker.id = content_order.worker_id left join luch_schema.order on content_order.order_id = luch_schema.order.id left join luch_schema.client on client.id = luch_schema.order.client_id where luch_schema.order.status = 'paid'  union all select distinct worker.full_name, client.full_name as client, 0 as price from luch_schema.worker left join luch_schema.content_order on worker.id = content_order.worker_id  left join luch_schema.order on content_order.order_id = luch_schema.order.id left join luch_schema.client on client.id = luch_schema.order.client_id where luch_schema.order.status = 'non-paid' union all select distinct worker.full_name, '-' as client, 0 as price from luch_schema.worker where not exists (select * from luch_schema.content_order where content_order.worker_id = worker.id) where not exists (select * from luch_schema.content_order, luch_schema.worker where content_order.worker_id = worker.id);
-- 'Вывести список сотрудников, работающих в данный момент над заказами (статус заказа - не оплачен)’
select distinct worker.full_name from luch_schema.worker join luch_schema.content_order on worker.id = content_order.worker_id join luch_schema.order on content_order.order_id = luch_schema.order.id where worker.id = any(select worker_id from luch_schema.content_order) and luch_schema.order.status = 'non-paid' ;
-- 'Вывести список сотрудников, их должность и количество обработанных ими заказов (выполненные + текущие)’
select worker.full_name as worker, worker.profession, count(luch_schema.order.id) from luch_schema.worker full join luch_schema.content_order on worker.id = content_order.worker_id  full join luch_schema.order on content_order.order_id = luch_schema.order.id where worker.profession in ('designer') group by worker.id;
-- 'Вывести список клиентов и сумму их заказов за весь период’
select client.full_name as client, sum(final_price) from luch_schema.client join luch_schema.order on client.id = luch_schema.order.client_id join luch_schema.content_order on luch_schema.order.id = content_order.order_id group by client.id;
